name: releaser

on:
  push:
    # do not consider simples commit
    branches:
      - '!*'
    # consider only release and pre-release tags
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: cache go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: tests modules
        run: |
          # This project does not vendorize it's dependencies.
          # go mod vendor
          # if [ ! -z "$(git status --porcelain)" ]; then
          #   echo "::error::vendor directory if not synced with go.mod, please run go mod vendor"
          #   exit 1
          # fi

          go mod tidy
          if [ ! -z "$(git status --porcelain)" ]; then
            echo "::error::modules are not tidy, please run go mod tidy"
            exit 1
          fi

      - name: tests
        run: |
          go test -v ./...

      - name: package
        run: |
          source .envrc
          go get github.com/cloudfoundry/libbuildpack/packager/buildpack-packager
          go install github.com/cloudfoundry/libbuildpack/packager/buildpack-packager
          buildpack-packager build -any-stack -version "${GITHUB_REF_NAME:1}"
          buildpack-packager build -stack=cflinuxfs3 -version "${GITHUB_REF_NAME:1}"
          buildpack-packager build -stack=cflinuxfs4 -version "${GITHUB_REF_NAME:1}"
          buildpack-packager build -cached -any-stack -version "${GITHUB_REF_NAME:1}"
          buildpack-packager build -cached -stack=cflinuxfs3 -version "${GITHUB_REF_NAME:1}"
          buildpack-packager build -cached -stack=cflinuxfs4 -version "${GITHUB_REF_NAME:1}"

      - name: create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            sidecars_buildpack-*.zip
          tag_name: ${{ github.ref_name }}
          body: |
            ${{ github.event.release.body }}
          draft: false
          prerelease: false
