name: unit-tests

on:
  pull_request: ~
  push: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: cache go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: tests
        run: |
          go test -v ./...

      - name: build bin/supply
        run: |
          GOOS=linux go build -ldflags="-s -w" -o bin/supply ./src/sidecars/supply/cli

      - name: build bin/build
        run: |
          GOOS=linux go build -ldflags="-s -w" -o bin/build ./src/sidecars/build/cli

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.0

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: package
        run: |
          source .envrc
          go get github.com/cloudfoundry/libbuildpack/packager/buildpack-packager
          go install github.com/cloudfoundry/libbuildpack/packager/buildpack-packager
          buildpack-packager build -any-stack -version "${GITHUB_REF_NAME:1}"
          buildpack-packager build -stack=cflinuxfs3 -version "${{ steps.semvers.outputs.patch }}+dev.1"
          buildpack-packager build -stack=cflinuxfs4 -version "${{ steps.semvers.outputs.patch }}+dev.1"
          buildpack-packager build -cached -any-stack -version "${{ steps.semvers.outputs.patch }}+dev.1"
          buildpack-packager build -cached -stack=cflinuxfs3 -version "${{ steps.semvers.outputs.patch }}+dev.1"
          buildpack-packager build -cached -stack=cflinuxfs4 -version "${{ steps.semvers.outputs.patch }}+dev.1"
