name: unit-tests

on:
  pull_request: ~
  push: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: cache go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: tests
        run: |
          go test -v ./...

      - name: build bin/supply
        run: |
          GOOS=linux go build -ldflags="-s -w" -o bin/supply ./src/sidecars/supply/cli

      - name: build bin/build
        run: |
          GOOS=linux go build -ldflags="-s -w" -o bin/build ./src/sidecars/build/cli

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.0

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: set version file
        run: |
          echo "${{ steps.semvers.outputs.patch }}+dev.1" > VERSION

      - name: package uncached any stack
        run: |
          BUNDLE_GEMFILE=cf.Gemfile bundle
          BUNDLE_GEMFILE=cf.Gemfile bundle exec buildpack-packager --uncached --any-stack

      - name: package uncached for cflinuxfs3
        run: |
          BUNDLE_GEMFILE=cf.Gemfile bundle
          BUNDLE_GEMFILE=cf.Gemfile bundle exec buildpack-packager --uncached --stack cflinuxfs3

      - name: package uncached for cflinuxfs4
        run: |
          BUNDLE_GEMFILE=cf.Gemfile bundle
          BUNDLE_GEMFILE=cf.Gemfile bundle exec buildpack-packager --uncached --stack cflinuxfs4

      - name: package cached any stack
        run: |
          BUNDLE_GEMFILE=cf.Gemfile bundle
          BUNDLE_GEMFILE=cf.Gemfile bundle exec buildpack-packager --cached --any-stack

      - name: package cached for cflinuxfs3
        run: |
          BUNDLE_GEMFILE=cf.Gemfile bundle
          BUNDLE_GEMFILE=cf.Gemfile bundle exec buildpack-packager --cached --stack cflinuxfs3

      - name: package cached for cflinuxfs4
        run: |
          BUNDLE_GEMFILE=cf.Gemfile bundle
          BUNDLE_GEMFILE=cf.Gemfile bundle exec buildpack-packager --cached --stack cflinuxfs4
