name: unit-tests

on:
  pull_request: ~
  push: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: cache go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: "${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}"
          restore-keys: |
            ${{ runner.os }}-go-

      - name: tests
        run: |
          go test -v ./...

      - name: build bin/supply
        run: |
          GOOS=linux go build -ldflags="-s -w" -o bin/supply ./src/sidecars/supply/cli

      - name: build bin/build
        run: |
          GOOS=linux go build -ldflags="-s -w" -o bin/build ./src/sidecars/build/cli

      - name: package
        run: |
          source .envrc
          export GOFLAGS=-mod=readonly
          go get github.com/cloudfoundry/libbuildpack/packager/buildpack-packager
          go install github.com/cloudfoundry/libbuildpack/packager/buildpack-packager
          buildpack-packager build -cachedir .cache -any-stack -version "${GITHUB_SHA}"
          buildpack-packager build -cachedir .cache -stack=cflinuxfs4 -version "${GITHUB_SHA}"
          buildpack-packager build -cachedir .cache -cached -any-stack -version "${GITHUB_SHA}"
          buildpack-packager build -cachedir .cache -cached -stack=cflinuxfs4 -version "${GITHUB_SHA}"
